export const patients = [
  // ── Patients hospitalisés ─────────────────────────────────────────────────
  {
    id: 'DEM-2026-001',
    name: 'Amine Mansouri',
    initials: 'AM',
    age: 27,
    gender: 'M',
    type: 'hospitalise',
    room: '12',
    bed: 'A',
    status: 'À surveiller',
    updated: '19:10',
    tone: 'blue',
  },
  {
    id: 'DEM-2026-002',
    name: 'Sarah Benali',
    initials: 'SB',
    age: 34,
    gender: 'F',
    type: 'hospitalise',
    room: '14',
    bed: 'B',
    status: 'Stable',
    updated: '18:45',
    tone: 'violet',
  },
  {
    id: 'DEM-2026-003',
    name: 'Yacine Aït',
    initials: 'YA',
    age: 52,
    gender: 'M',
    type: 'hospitalise',
    room: '15',
    bed: 'A',
    status: 'Urgent',
    updated: '18:30',
    tone: 'orange',
  },
  {
    id: 'DEM-2026-004',
    name: 'Nadia Cherif',
    initials: 'NC',
    age: 46,
    gender: 'F',
    type: 'hospitalise',
    room: '16',
    bed: 'B',
    status: 'Stable',
    updated: '18:12',
    tone: 'green',
  },
  {
    id: 'DEM-2026-005',
    name: 'Lina Haddad',
    initials: 'LH',
    age: 62,
    gender: 'F',
    type: 'hospitalise',
    room: '18',
    bed: 'A',
    status: 'Stable',
    updated: '17:50',
    tone: 'rose',
  },
  {
    id: 'DEM-2026-006',
    name: 'Omar Meziane',
    initials: 'OM',
    age: 39,
    gender: 'M',
    type: 'hospitalise',
    room: '19',
    bed: 'B',
    status: 'Sortie',
    updated: '17:20',
    tone: 'slate',
  },
  {
    id: 'DEM-2026-007',
    name: 'Khalid Benmoussa',
    initials: 'KB',
    age: 58,
    gender: 'M',
    type: 'hospitalise',
    room: '20',
    bed: 'A',
    status: 'Stable',
    updated: '16:55',
    tone: 'blue',
  },
  {
    id: 'DEM-2026-008',
    name: 'Fatima Zahra Oukaci',
    initials: 'FZ',
    age: 44,
    gender: 'F',
    type: 'hospitalise',
    room: '21',
    bed: 'B',
    status: 'Urgent',
    updated: '16:40',
    tone: 'rose',
  },

  // ── Hôpital du jour (ambulatoire) ─────────────────────────────────────────
  // Patients qui viennent pour des soins journaliers et repartent à domicile
  {
    id: 'HDJ-2026-001',
    name: 'Rachid Boumediène',
    initials: 'RB',
    age: 55,
    gender: 'M',
    type: 'jour',
    room: 'HDJ-1',
    bed: '—',
    status: 'Stable',
    updated: '09:15',
    tone: 'blue',
    motif: 'Séance de chimiothérapie',
  },
  {
    id: 'HDJ-2026-002',
    name: 'Meriem Taleb',
    initials: 'MT',
    age: 38,
    gender: 'F',
    type: 'jour',
    room: 'HDJ-2',
    bed: '—',
    status: 'Stable',
    updated: '10:30',
    tone: 'green',
    motif: 'Transfusion sanguine',
  },
  {
    id: 'HDJ-2026-003',
    name: 'Ali Ferhat',
    initials: 'AF',
    age: 67,
    gender: 'M',
    type: 'jour',
    room: 'HDJ-3',
    bed: '—',
    status: 'À surveiller',
    updated: '11:00',
    tone: 'orange',
    motif: 'Perfusion IV bihebdomadaire',
  },
]
